version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - TAG=commit-"$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
      - echo Using NAME "$APPLICATION_NAME"
      - echo Using TAG "$TAG"
      - echo Using IMAGE_URI "$IMAGE_URI"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t "${APPLICATION_NAME}:latest" --no-cache .
      - docker tag "${APPLICATION_NAME}:latest" "${REPOSITORY_URI}:latest"
      - docker tag "${APPLICATION_NAME}:latest" "${REPOSITORY_URI}:${TAG}"
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push "${REPOSITORY_URI}:latest"
      - docker push "${REPOSITORY_URI}:${TAG}"
      - echo Preparing Cloudformation Artifacts
      - printf '[{"name":"%s","imageUri":"%s"}]' "$APPLICATION_NAME" "$IMAGE_URI" > images.json
      - cat images.json
      - printf '{"Parameters":{"ContainerImage":"%s","ContainerName":"%s","SensuCommand":"api"}}' "$IMAGE_URI" "$APPLICATION_NAME"-api-default > sensu-api-stack-configuration.json
      - cat sensu-api-stack-configuration.json
      - printf '{"Parameters":{"ContainerImage":"%s","ContainerName":"%s","SensuCommand":"server"}}' "$IMAGE_URI" "$APPLICATION_NAME"-server-default > sensu-server-stack-configuration.json
      - cat sensu-server-stack-configuration.json
      - sed "s|SSM_BASE_PATH|$SSM_BASE_PATH_DEV|g" cloudformation-sensu-api.json > cloudformation-sensu-api-dev.json
      - cat cloudformation-sensu-api-dev.json
      - sed "s|SSM_BASE_PATH|$SSM_BASE_PATH_PREPROD|g" cloudformation-sensu-api.json > cloudformation-sensu-api-preprod.json
      - cat cloudformation-sensu-api-preprod.json
      - sed "s|SSM_BASE_PATH|$SSM_BASE_PATH_PROD|g" cloudformation-sensu-api.json > cloudformation-sensu-api-prod.json
      - cat cloudformation-sensu-api-prod.json
      - sed "s|SSM_BASE_PATH|$SSM_BASE_PATH_DEV|g" cloudformation-sensu-server.json > cloudformation-sensu-server-dev.json
      - cat cloudformation-sensu-server-dev.json
      - sed "s|SSM_BASE_PATH|$SSM_BASE_PATH_PREPROD|g" cloudformation-sensu-server.json > cloudformation-sensu-server-preprod.json
      - cat cloudformation-sensu-server-preprod.json
      - sed "s|SSM_BASE_PATH|$SSM_BASE_PATH_PROD|g" cloudformation-sensu-server.json > cloudformation-sensu-server-prod.json
      - cat cloudformation-sensu-server-prod.json

artifacts:
  files:
    - images.json
    - sensu-api-stack-configuration.json
    - sensu-server-stack-configuration.json
    - cloudformation-sensu-api.json
    - cloudformation-sensu-api-dev.json
    - cloudformation-sensu-api-preprod.json
    - cloudformation-sensu-api-prod.json
    - cloudformation-sensu-server.json
    - cloudformation-sensu-server-dev.json
    - cloudformation-sensu-server-preprod.json
    - cloudformation-sensu-server-prod.json
