version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - TAG=commit-"$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
      - echo Using NAME "$APPLICATION_NAME"
      - echo Using CUSTOMER_NAME "$CUSTOMER_NAME"
      - echo Using TAG "$TAG"
      - echo Using IMAGE_URI "$IMAGE_URI"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t "${APPLICATION_NAME}:latest" --no-cache .
      - docker tag "${APPLICATION_NAME}:latest" "${REPOSITORY_URI}:latest"
      - docker tag "${APPLICATION_NAME}:latest" "${REPOSITORY_URI}:${TAG}"
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push "${REPOSITORY_URI}:latest"
      - docker push "${REPOSITORY_URI}:${TAG}"
